---
# Deploy the full 3Scale demo 

- hosts: localhost

  roles:
    - ocp_login
    - install_postgres
    - install_registry
    - sso
    - configure_sso
    - 3scale
    - configure_3Scale_tenant
    - install3ScaleAPIs