---

- name: Add the wildcard domain to the OpenAPI Docs
  template:
    src: '{{ role_path }}/files/{{ api }}.j2'
    dest: /tmp/{{ api }}.yaml

- name: Add v2 customer management API
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    definition:
      apiVersion: capabilities.3scale.net/v1beta1
      kind: Backend
      metadata:
        name: customer-management-api-v2
        namespace: amp
      spec:
        providerAccountRef:
          name: red-hat-tenant
        name: customer-management-api-v2
        privateBaseURL: 'http://membersdemov2.membersapp.svc.cluster.local:80'
        systemName: customer-management-api-v2
        description: Customer Management API Backend v2

- name: Add v1 customer management API
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    definition:
      apiVersion: capabilities.3scale.net/v1beta1
      kind: Backend
      metadata:
        name: 'customer-management-api-v1'
        namespace: amp
      spec:
        providerAccountRef:
          name: red-hat-tenant
        name: customer_management-api-v1
        privateBaseURL: 'http://membersdemov1.membersapp.svc.cluster.local:80'
        systemName: customer-management-api-v1
        description: Customer Management API Backend v1

- name: Add customer management API product API
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    definition:
      apiVersion: capabilities.3scale.net/v1beta1
      kind: Product
      metadata:
        name: customer-management-api
      spec:
        metrics:
          hits:
            description: Number of API hits
            friendlyName: Hits
            unit: hit
          v1:
            description: Count of calls to the v1 API
            friendlyName: v1
            unit: count
          v2:
            description: Count of calls to the v2 API
            friendlyName: v2
            unit: count
        deployment:
          apicastHosted:
            authentication:
              userkey:
                authUserKey: user-key
                credentials: headers
        backendUsages:
          customer-management-api-v1:
            path: /v1
          customer-management-api-v2:
            path: /v2
        mappingRules:
          - httpMethod: GET
            increment: 1
            metricMethodRef: listAllMembers
            pattern: '/{version}/membersweb/rest/members$'
          - httpMethod: POST
            increment: 1
            metricMethodRef: createMember
            pattern: '/{version}/membersweb/rest/members$'
          - httpMethod: GET
            increment: 1
            metricMethodRef: hello
            pattern: '/{version}/membersweb/rest/members/hello$'
          - httpMethod: DELETE
            increment: 1
            metricMethodRef: deleteMember
            pattern: '/{version}/membersweb/rest/members/{email}$'
          - httpMethod: GET
            increment: 1
            metricMethodRef: lookupMemberById
            pattern: '/{version}/membersweb/rest/members/{id}$'
          - httpMethod: POST
            increment: 1
            metricMethodRef: v1
            pattern: /v1
          - httpMethod: DELETE
            increment: 1
            metricMethodRef: v1
            pattern: /v1
          - httpMethod: GET
            increment: 1
            metricMethodRef: v1
            pattern: /v1
          - httpMethod: POST
            increment: 1
            metricMethodRef: v2
            pattern: /v2
          - httpMethod: DELETE
            increment: 1
            metricMethodRef: v2
            pattern: /v2
          - httpMethod: GET
            increment: 1
            metricMethodRef: v2
            pattern: /v2
        name: Customer Management API
        policies:
          - configuration: {}
            configurationRef: {}
            enabled: true
            name: apicast
            version: builtin
        methods:
          createMember:
            description: Create Member
            friendlyName: createMember
          deleteMember:
            description: Delete Member
            friendlyName: delete member
          hello:
            description: Hello
            friendlyName: hello
          listAllMembers:
            description: List all Members
            friendlyName: list All Members
          lookupMemberById:
            description: lookup Member By Id
            friendlyName: lookup Member By Id
        providerAccountRef:
          name: red-hat-tenant
        systemName: Custome-Management-API
        applicationPlans:
          bronze-members-plans-v1:
            appsRequireApproval: true
            costMonth: '10'
            limits:
              - metricMethodRef:
                  systemName: listAllMembers
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: createMember
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: hello
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: deleteMember
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: lookupMemberById
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: v1
                period: day
                value: 10000
            pricingRules:
              - metricMethodRef:
                  systemName: listAllMembers
                pricePerUnit: "0.25"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: createMember
                pricePerUnit: "0.50"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: deleteMember
                pricePerUnit: "0.25"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: lookupMemberById
                pricePerUnit: "0.25"
                from: 1
                to: 1000
            name: Bronze Members Plan V1
            published: true
            setupFee: '25'
            trialPeriod: 10
          bronze-members-plans-v2:
            appsRequireApproval: true
            costMonth: '10'
            limits:
              - metricMethodRef:
                  systemName: listAllMembers
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: createMember
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: hello
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: deleteMember
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: lookupMemberById
                period: minute
                value: 40
              - metricMethodRef:
                  systemName: v1
                period: day
                value: 10000
            pricingRules:
              - metricMethodRef:
                  systemName: listAllMembers
                pricePerUnit: "0.25"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: createMember
                pricePerUnit: "0.50"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: deleteMember
                pricePerUnit: "0.25"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: lookupMemberById
                pricePerUnit: "0.25"
                from: 1
                to: 1000
            name: Bronze Members Plan V2
            published: true
            setupFee: '25'
            trialPeriod: 10
          restricted-bronze-members-plans-v1:
            appsRequireApproval: true
            costMonth: '10'
            limits:
              - metricMethodRef:
                  systemName: listAllMembers
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: createMember
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: hello
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: deleteMember
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: lookupMemberById
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: v1
                period: day
                value: 10000
            pricingRules:
              - metricMethodRef:
                  systemName: listAllMembers
                pricePerUnit: "0.25"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: createMember
                pricePerUnit: "0.50"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: deleteMember
                pricePerUnit: "0.25"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: lookupMemberById
                pricePerUnit: "0.25"
                from: 1
                to: 1000
            name: Restricted Bronze Members Plan V1
            published: true
            setupFee: '25'
            trialPeriod: 10
          restricted-bronze-members-plans-v2:
            appsRequireApproval: true
            costMonth: '10'
            limits:
              - metricMethodRef:
                  systemName: listAllMembers
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: createMember
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: hello
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: deleteMember
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: lookupMemberById
                period: minute
                value: 10
              - metricMethodRef:
                  systemName: v1
                period: day
                value: 10000
            pricingRules:
              - metricMethodRef:
                  systemName: listAllMembers
                pricePerUnit: "0.25"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: createMember
                pricePerUnit: "0.50"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: deleteMember
                pricePerUnit: "0.25"
                from: 1
                to: 1000
              - metricMethodRef:
                  systemName: lookupMemberById
                pricePerUnit: "0.25"
                from: 1
                to: 1000
            name: RestrictedBronze Members Plan V2
            published: true
            setupFee: '25'
            trialPeriod: 10
        description: Customer Management API






- name: Add customer management API product API
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    definition:
      apiVersion: capabilities.3scale.net/v1beta1
      kind: ProxyConfigPromote
      metadata:
        name: promote-customer-management-aoi
      spec:
        deleteCR: true
        productCRName: customer-management-api
        production: true


- name: Add the Activedoc to 3scale - user key auth
  k8s:
    api_key: "{{ ocp_login_token }}"
    host: "{{ ocp_url }}"
    validate_certs: no
    state: present
    definition:
      apiVersion: capabilities.3scale.net/v1beta1
      kind: ActiveDoc
      metadata:
        name: customer-management-api-v2
        namespace: amp
      spec:
        providerAccountRef:
          name: red-hat-tenant
        activeDocOpenAPIRef:
          url: 'http://example-apicurioregistry-mem.registry.router-default.apps.cluster-skvj7.dynamic.redhatworkshops.io/apis/registry/v2/groups/philorg/artifacts/customerapi/versions/1'
        name: customer-management-api-v2
        published: true
        description: Customer Management API
        productSystemName: Customer-Management-API
  when: (api == "membersregistration_spec")

# API installed, need to add the similar for the oauth version

- name: Change the OAuth service to OIDC type Authentication 
  uri:
    validate_certs: no
    method: PUT
    url: "https://{{ api_tenant }}-admin.{{ wildcarddomain }}/admin/api/services/{{ serviceid }}.json"
    status_code: 200
    body_format: form-urlencoded
    body:
      access_token: "{{ tenanttoken }}"
      backend_version: "oidc"
  ignore_errors: yes
  when: (api == "membersregistration_spec_oauth")

- name: Update the Oauth APi with details of SSO 
  uri:
    validate_certs: no
    method: PATCH
    url: "https://{{ api_tenant }}-admin.{{ wildcarddomain }}/admin/api/services/{{ serviceid }}/proxy.json"
    status_code: 200
    body_format: form-urlencoded
    body:
      access_token: "{{ tenanttoken }}"
      oidc_issuer_endpoint: "http://3scale-admin:3scale-admin-secret@sso-sso-clear.{{ wildcarddomain }}/auth/realms/3scale"
      oidc_issuer_type: "keycloak"
      jwt_claim_with_client_id: "azp"
      jwt_claim_with_client_id_type: "plain"
  ignore_errors: yes
  when: (api == "membersregistration_spec_oauth")

- name: Deploy API to Staging Gateway  
  uri:
    validate_certs: no
    method: POST
    url: "https://{{ api_tenant }}-admin.{{ wildcarddomain }}/admin/api/services/{{ serviceid }}/proxy/deploy.json"
    status_code: 201,422
    body_format: form-urlencoded
    body:
      access_token: "{{ tenanttoken }}"
  ignore_errors: yes

- name: Get latest vesion deployed to staging gateway
  uri:
    validate_certs: no
    method: GET
    url: "https://{{ api_tenant }}-admin.{{ wildcarddomain }}/admin/api/services/{{ serviceid }}/proxy/configs/sandbox/latest.json?access_token={{ tenanttoken }}"
    body_format: json
  ignore_errors: yes
  register: "lastest_version_doc"

- name: Get the latest version number
  set_fact:
    version_id: "{{ lastest_version_doc.json.proxy_config.version }}"
  ignore_errors: yes

- name: Promote to Production Gateway 
  uri:
    validate_certs: no
    method: POST
    url: "https://{{ api_tenant }}-admin.{{ wildcarddomain }}/admin/api/services/{{ serviceid }}/proxy/configs/sandbox/{{ version_id }}/promote.json"
    status_code: 201,422
    body_format: form-urlencoded
    body:
      access_token: "{{ tenanttoken }}"
      to: "production"
  ignore_errors: yes

- name: Process Applications Plans
  include_tasks: process_application_plans.yml
  ignore_errors: yes