---
- name: Add Applications Plan for the members api
  uri:
    validate_certs: no
    method: POST
    url: "https://{{ api_tenant }}-admin.{{ wildcarddomain }}/admin/api/services/{{ serviceid }}/application_plans.json"
    status_code: 201,422
    body_format: form-urlencoded
    body:
      access_token: "{{ tenanttoken }}"
      name: "{{ item[0] }} Members Plans V{{ item[1] }}"
      approval_required: false
      cost_per_month: 10
      setup_fee: 25
      trial_period_days: 10
      state_event: "publish"
  with_nested: 
    - ["Restricted", "Bronze"]
    - ['1', '2']
  ignore_errors: yes
  register: application_plans

- name: Find all metrics defined to the Members api
  uri:
    validate_certs: no
    body_format: raw
    method: GET
    url: "https://{{ api_tenant }}-admin.{{ wildcarddomain }}/admin/api/services/{{ serviceid }}/metrics.json?access_token={{ tenanttoken }}"
  register: metrics_list

- name: Loop over Applications Plans
  include_tasks: loop_over_metrics.yml
  loop: "{{ application_plans.results }}"
  loop_control:
    loop_var: appplan
  ignore_errors: yes