---
kind: Secret
apiVersion: v1
metadata:
  name: credential-3scale-sso
  namespace: sso
  labels:
    app: keycloak
    keycloak: 3scale-sso
stringData:
  ADMIN_PASSWORD: admin
  ADMIN_USERNAME: "{{ ssopassword }}"
type: Opaque
